version: '3.9'

services:
  helloworld:
    build:
      context: .
      dockerfile: build/helloworld.Dockerfile
    ports:
      - "1323:1323"
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
